#define TraceStoreEventIndex                                                   0
#define TraceStoreEventAllocationIndex                                         1
#define TraceStoreEventAddressIndex                                            2
#define TraceStoreEventInfoIndex                                               3
#define TraceStoreStringIndex                                                  4
#define TraceStoreStringAllocationIndex                                        5
#define TraceStoreStringAddressIndex                                           6
#define TraceStoreStringInfoIndex                                              7
#define TraceStoreStringBufferIndex                                            8
#define TraceStoreStringBufferAllocationIndex                                  9
#define TraceStoreStringBufferAddressIndex                                    10
#define TraceStoreStringBufferInfoIndex                                       11
#define TraceStoreHashedStringIndex                                           12
#define TraceStoreHashedStringAllocationIndex                                 13
#define TraceStoreHashedStringAddressIndex                                    14
#define TraceStoreHashedStringInfoIndex                                       15
#define TraceStoreHashedStringBufferIndex                                     16
#define TraceStoreHashedStringBufferAllocationIndex                           17
#define TraceStoreHashedStringBufferAddressIndex                              18
#define TraceStoreHashedStringBufferInfoIndex                                 19
#define TraceStoreBufferIndex                                                 20
#define TraceStoreBufferAllocationIndex                                       21
#define TraceStoreBufferAddressIndex                                          22
#define TraceStoreBufferInfoIndex                                             23
#define TraceStoreFunctionTableIndex                                          24
#define TraceStoreFunctionTableAllocationIndex                                25
#define TraceStoreFunctionTableAddressIndex                                   26
#define TraceStoreFunctionTableInfoIndex                                      27
#define TraceStoreFunctionTableEntryIndex                                     28
#define TraceStoreFunctionTableEntryAllocationIndex                           29
#define TraceStoreFunctionTableEntryAddressIndex                              30
#define TraceStoreFunctionTableEntryInfoIndex                                 31
#define TraceStorePathTableIndex                                              32
#define TraceStorePathTableAllocationIndex                                    33
#define TraceStorePathTableAddressIndex                                       34
#define TraceStorePathTableInfoIndex                                          35
#define TraceStorePathTableEntryIndex                                         36
#define TraceStorePathTableEntryAllocationIndex                               37
#define TraceStorePathTableEntryAddressIndex                                  38
#define TraceStorePathTableEntryInfoIndex                                     39
#define TraceStoreSessionIndex                                                40
#define TraceStoreSessionAllocationIndex                                      41
#define TraceStoreSessionAddressIndex                                         42
#define TraceStoreSessionInfoIndex                                            43
#define TraceStoreFilenameStringIndex                                         44
#define TraceStoreFilenameStringAllocationIndex                               45
#define TraceStoreFilenameStringAddressIndex                                  46
#define TraceStoreFilenameStringInfoIndex                                     47
#define TraceStoreFilenameStringBufferIndex                                   48
#define TraceStoreFilenameStringBufferAllocationIndex                         49
#define TraceStoreFilenameStringBufferAddressIndex                            50
#define TraceStoreFilenameStringBufferInfoIndex                               51
#define TraceStoreDirectoryStringIndex                                        52
#define TraceStoreDirectoryStringAllocationIndex                              53
#define TraceStoreDirectoryStringAddressIndex                                 54
#define TraceStoreDirectoryStringInfoIndex                                    55
#define TraceStoreDirectoryStringBufferIndex                                  56
#define TraceStoreDirectoryStringBufferAllocationIndex                        57
#define TraceStoreDirectoryStringBufferAddressIndex                           58
#define TraceStoreDirectoryStringBufferInfoIndex                              59
#define TraceStoreStringArrayIndex                                            60
#define TraceStoreStringArrayAllocationIndex                                  61
#define TraceStoreStringArrayAddressIndex                                     62
#define TraceStoreStringArrayInfoIndex                                        63
#define TraceStoreStringTableIndex                                            64
#define TraceStoreStringTableAllocationIndex                                  65
#define TraceStoreStringTableAddressIndex                                     66
#define TraceStoreStringTableInfoIndex                                        67
#define MAX_TRACE_STORES                                                      68
