pgomgr /merge Python.pgd
pgomgr /merge PythonProject.pgd
pgomgr /merge PythonTracer.pgd
pgomgr /merge Rtl.pgd
pgomgr /merge StringTable.pgd
pgomgr /merge TlsTracerHeap.pgd
pgomgr /merge tpython.pgd
pgomgr /merge TracedPythonSession.pgd
pgomgr /merge TracerConfig.pgd
pgomgr /merge TracerHeap.pgd
pgomgr /merge TraceStore.pgd
